/**
 * Output item types that can be displayed in the output panel
 */
export type OutputType = 'script' | 'script-output' | 'image' | 'iframe';

/**
 * Base interface with common properties for all output items
 */
interface OutputItemBase {
  /** Unique identifier for this output */
  id: string;
  
  /** Timestamp when the output was created (milliseconds since epoch) */
  timestamp: number;
  
  /** The actual content to display */
  content: string;
}

/**
 * Script output - shows the script that will be/was executed
 */
export interface ScriptOutput extends OutputItemBase {
  type: 'script';
  metadata?: {
    pendingApproval?: boolean;
    approved?: boolean;
    denied?: boolean;
    serverHealthCheck?: 'checking' | 'healthy' | 'unhealthy';
    serverError?: string;
    executionStatus?: 'running' | 'completed' | 'failed';
    scriptType?: 'python' | 'shell';
  };
}

/**
 * Script execution output - shows the result of running a script
 */
export interface ScriptExecutionOutput extends OutputItemBase {
  type: 'script-execution-output';
  metadata: {
    exitCode: number;
    scriptPath: string;
    stderr?: string;
    scriptType?: 'python' | 'shell';
  };
}

/**
 * Image output - shows an image file generated by a script
 */
export interface ImageOutput extends OutputItemBase {
  type: 'image';
  metadata: {
    relativePath: string;
    mimeType: string;
  };
}

/**
 * Iframe output - shows an embedded iframe with a given URL
 */
export interface IframeOutput extends OutputItemBase {
  type: 'iframe';
  metadata: {
    url: string;
    title?: string;
  };
}

/**
 * Discriminated union of all output item types
 */
export type OutputItem = ScriptOutput | ScriptExecutionOutput | ImageOutput | IframeOutput;

/**
 * Function signature for emitting outputs from tools
 */
export type OutputEmitter = (output: Omit<OutputItem, 'id' | 'timestamp'>) => string;
